export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  SERVICES: "/services",
  EXPERIENCE: "/experience",
  TESTIMONIALS: "/testimonials",
  PROJECTS: "/projects",
  PROJECT: (slug: string) => `/projects/${encodeURIComponent(slug)}`,
  BLOG: "/blog",
  ARTICLE: (slug: string) => `/blog/${encodeURIComponent(slug)}`,
  SIGN_IN: "/auth/sign-in",
  SIGN_UP: "/auth/sign-up",
  ADMIN: "/admin",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_PROJECT_NEW: "/admin/projects/new",
  ADMIN_PROJECT_EDIT: (slug: string) => `/admin/projects/${encodeURIComponent(slug)}/edit`,
  ADMIN_SERVICES: "/admin/services",
  ADMIN_SERVICE_NEW: "/admin/services/new",
  ADMIN_SERVICE_EDIT: (slug: string) => `/admin/services/${encodeURIComponent(slug)}/edit`,
  ADMIN_EXPERIENCE: "/admin/experience",
  ADMIN_EXPERIENCE_NEW: "/admin/experience/new",
  ADMIN_EXPERIENCE_EDIT: (slug: string) => `/admin/experience/${encodeURIComponent(slug)}/edit`,
  ADMIN_SKILLS: "/admin/skills",
  ADMIN_SKILL_NEW: "/admin/skills/new",
  ADMIN_SKILL_EDIT: (slug: string) => `/admin/skills/${encodeURIComponent(slug)}/edit`,
  ADMIN_TESTIMONIALS: "/admin/testimonials",
  ADMIN_TESTIMONIAL_NEW: "/admin/testimonials/new",
  ADMIN_TESTIMONIAL_EDIT: (slug: string) => `/admin/testimonials/${encodeURIComponent(slug)}/edit`,
  ADMIN_ARTICLES: "/admin/articles",
  ADMIN_ARTICLE_NEW: "/admin/articles/new",
  ADMIN_ARTICLE_EDIT: (slug: string) => `/admin/articles/${encodeURIComponent(slug)}/edit`,
  ADMIN_CONTACT_MESSAGES: "/admin/contact-messages",
  ADMIN_USERS: "/admin/users",
  ADMIN_SETTINGS: "/admin/settings",
} as const;
